### Criação de um novo contato
POST http://localhost:5000/api/contatos
Content-Type: application/json

{
  "nome": "João pereira",
  "email": "joao.silva@hotmail.com",
  "telefone": "13345655789",
  "cargo": "Gerente de Vendas",
  "empresa": "67102b5b337de1c528d441ea"
}

### Criação de um novo usuário
POST http://localhost:5000/api/usuarios
Content-Type: application/json

{
  "nome": "Maria alves",
  "email": "maria.silva@gmail.com",
  "senha": "senhaSegura12453"
}

###
POST http://localhost:5000/api/reunioes
Content-Type: application/json

{
  "title": "Reunião de Planejamento",
  "date": "2024-12-02",
  "time": "15:00"
}

###
GET http://localhost:5000/api/reunioes?date=2024-12-25
Content-Type: application/json
